# Generated by Django 3.2.5 on 2023-02-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_nc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tt_audio1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta', models.IntegerField()),
                ('ga', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='tt_audio',
        ),
    ]
