# Generated by Django 3.2.5 on 2023-03-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_nc', '0002_auto_20230228_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tt_audio1',
            old_name='ga',
            new_name='audio_file',
        ),
        migrations.RemoveField(
            model_name='tt_audio1',
            name='ta',
        ),
    ]
